version: '3.8'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    init: true
    restart: always
    ports: 
      - 1972
      - 9192
      - 52795:52773
      - 53773
    volumes:
      - ./:/irisdev/app
